# Etapa 1: Build de la app
FROM node:20-alpine3 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servir la app
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

# Opcional: puedes sobrescribir la configuración de nginx si quieres
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
